//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace STDDatos
{
    public partial class BDDOCUMENTUMEntities : ObjectContext
    {
        public const string ConnectionString = "name=BDDOCUMENTUMEntities";
        public const string ContainerName = "BDDOCUMENTUMEntities";
    
        #region Constructors
    
        public BDDOCUMENTUMEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public BDDOCUMENTUMEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public BDDOCUMENTUMEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Cargo> Cargoes
        {
            get { return _cargoes  ?? (_cargoes = CreateObjectSet<Cargo>("Cargoes")); }
        }
        private ObjectSet<Cargo> _cargoes;
    
        public ObjectSet<Expediente> Expedientes
        {
            get { return _expedientes  ?? (_expedientes = CreateObjectSet<Expediente>("Expedientes")); }
        }
        private ObjectSet<Expediente> _expedientes;
    
        public ObjectSet<Solicitante> Solicitantes
        {
            get { return _solicitantes  ?? (_solicitantes = CreateObjectSet<Solicitante>("Solicitantes")); }
        }
        private ObjectSet<Solicitante> _solicitantes;
    
        public ObjectSet<Tramite> Tramites
        {
            get { return _tramites  ?? (_tramites = CreateObjectSet<Tramite>("Tramites")); }
        }
        private ObjectSet<Tramite> _tramites;
    
        public ObjectSet<Tupa> Tupas
        {
            get { return _tupas  ?? (_tupas = CreateObjectSet<Tupa>("Tupas")); }
        }
        private ObjectSet<Tupa> _tupas;
    
        public ObjectSet<Evaluacion> Evaluacions
        {
            get { return _evaluacions  ?? (_evaluacions = CreateObjectSet<Evaluacion>("Evaluacions")); }
        }
        private ObjectSet<Evaluacion> _evaluacions;
    
        public ObjectSet<Usuario> Usuarios
        {
            get { return _usuarios  ?? (_usuarios = CreateObjectSet<Usuario>("Usuarios")); }
        }
        private ObjectSet<Usuario> _usuarios;

        #endregion
    }
}
