//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    [DataContract(IsReference = false)]
    [KnownType(typeof(Expediente))]
    public partial class Cargo
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> codigoExpediente
        {
            get { return _codigoExpediente; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_codigoExpediente != value)
                    {
                        if (Expediente != null && Expediente.codigo != value)
                        {
                            Expediente = null;
                        }
                        _codigoExpediente = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _codigoExpediente;
        [DataMember]
        public virtual Nullable<System.DateTime> FechaEmision
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Recepcionista
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Solicitante
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Estado
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Expediente Expediente
        {
            get { return _expediente; }
            set
            {
                if (!ReferenceEquals(_expediente, value))
                {
                    var previousValue = _expediente;
                    _expediente = value;
                    FixupExpediente(previousValue);
                }
            }
        }
        private Expediente _expediente;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupExpediente(Expediente previousValue)
        {
            if (previousValue != null && previousValue.Cargoes.Contains(this))
            {
                previousValue.Cargoes.Remove(this);
            }
    
            if (Expediente != null)
            {
                if (!Expediente.Cargoes.Contains(this))
                {
                    Expediente.Cargoes.Add(this);
                }
                if (codigoExpediente != Expediente.codigo)
                {
                    codigoExpediente = Expediente.codigo;
                }
            }
            else if (!_settingFK)
            {
                codigoExpediente = null;
            }
        }

        #endregion
    }
}
