//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Expediente))]
    public partial class Cargo
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> FechaEmision
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Recepcionista
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> codigoExpediente
        {
            get { return _codigoExpediente; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_codigoExpediente != value)
                    {
                        if (Expediente_1 != null && Expediente_1.codigo != value)
                        {
                            Expediente_1 = null;
                        }
                        _codigoExpediente = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _codigoExpediente;
        [DataMember]
        public virtual string Solicitante
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Estado
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Expediente Expediente_1
        {
            get { return _expediente_1; }
            set
            {
                if (!ReferenceEquals(_expediente_1, value))
                {
                    var previousValue = _expediente_1;
                    _expediente_1 = value;
                    FixupExpediente_1(previousValue);
                }
            }
        }
        private Expediente _expediente_1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupExpediente_1(Expediente previousValue)
        {
            if (previousValue != null && previousValue.Cargo_1.Contains(this))
            {
                previousValue.Cargo_1.Remove(this);
            }
    
            if (Expediente_1 != null)
            {
                if (!Expediente_1.Cargo_1.Contains(this))
                {
                    Expediente_1.Cargo_1.Add(this);
                }
                if (codigoExpediente != Expediente_1.codigo)
                {
                    codigoExpediente = Expediente_1.codigo;
                }
            }
            else if (!_settingFK)
            {
                codigoExpediente = null;
            }
        }

        #endregion
    }
}
