//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    //[DataContract(IsReference = true)]
    [DataContract(IsReference = false)]
    //[DataContract]
    public partial class Evaluacion
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigoExpediente
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Tramite
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Solicitante
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Estado
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Recepcionista
        {
            get;
            set;
        }

        #endregion
    }
}
