//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    [DataContract(IsReference = false)]
    [KnownType(typeof(Expediente))]
    public partial class Solicitante
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string nombre
        {
            get;
            set;
        }
        [DataMember]
        public virtual string apellido
        {
            get;
            set;
        }
        [DataMember]
        public virtual string dni
        {
            get;
            set;
        }
        [DataMember]
        public virtual string telefono
        {
            get;
            set;
        }
        [DataMember]
        public virtual string correo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string direccion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Expediente> Expedientes
        {
            get
            {
                if (_expedientes == null)
                {
                    var newCollection = new FixupCollection<Expediente>();
                    newCollection.CollectionChanged += FixupExpedientes;
                    _expedientes = newCollection;
                }
                return _expedientes;
            }
            set
            {
                if (!ReferenceEquals(_expedientes, value))
                {
                    var previousValue = _expedientes as FixupCollection<Expediente>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupExpedientes;
                    }
                    _expedientes = value;
                    var newValue = value as FixupCollection<Expediente>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupExpedientes;
                    }
                }
            }
        }
        private ICollection<Expediente> _expedientes;

        #endregion
        #region Association Fixup
    
        private void FixupExpedientes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Expediente item in e.NewItems)
                {
                    item.Solicitante = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Expediente item in e.OldItems)
                {
                    if (ReferenceEquals(item.Solicitante, this))
                    {
                        item.Solicitante = null;
                    }
                }
            }
        }

        #endregion
    }
}
