//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Expediente))]
    [KnownType(typeof(Tupa))]
    public partial class Tramite
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string nombre
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<Expediente> Expediente
        {
            get
            {
                if (_expediente == null)
                {
                    var newCollection = new FixupCollection<Expediente>();
                    newCollection.CollectionChanged += FixupExpediente;
                    _expediente = newCollection;
                }
                return _expediente;
            }
            set
            {
                if (!ReferenceEquals(_expediente, value))
                {
                    var previousValue = _expediente as FixupCollection<Expediente>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupExpediente;
                    }
                    _expediente = value;
                    var newValue = value as FixupCollection<Expediente>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupExpediente;
                    }
                }
            }
        }
        private ICollection<Expediente> _expediente;
        
    
        [DataMember]
        public virtual ICollection<Tupa> Tupa
        {
            get
            {
                if (_tupa == null)
                {
                    var newCollection = new FixupCollection<Tupa>();
                    newCollection.CollectionChanged += FixupTupa;
                    _tupa = newCollection;
                }
                return _tupa;
            }
            set
            {
                if (!ReferenceEquals(_tupa, value))
                {
                    var previousValue = _tupa as FixupCollection<Tupa>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTupa;
                    }
                    _tupa = value;
                    var newValue = value as FixupCollection<Tupa>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTupa;
                    }
                }
            }
        }
        private ICollection<Tupa> _tupa;

        #endregion
        #region Association Fixup
    
        private void FixupExpediente(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Expediente item in e.NewItems)
                {
                    item.Tramite = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Expediente item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tramite, this))
                    {
                        item.Tramite = null;
                    }
                }
            }
        }
    
        private void FixupTupa(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Tupa item in e.NewItems)
                {
                    item.Tramite = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Tupa item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tramite, this))
                    {
                        item.Tramite = null;
                    }
                }
            }
        }

        #endregion
    }
}
