//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace STDDatos
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tramite))]
    public partial class Tupa
    {
        #region Primitive Properties
        [DataMember]
        public virtual int codigo
        {
            get;
            set;
        }
        [DataMember]
        public virtual string nombre
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> codigoTramite
        {
            get { return _codigoTramite; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_codigoTramite != value)
                    {
                        if (Tramite != null && Tramite.codigo != value)
                        {
                            Tramite = null;
                        }
                        _codigoTramite = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _codigoTramite;

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual Tramite Tramite
        {
            get { return _tramite; }
            set
            {
                if (!ReferenceEquals(_tramite, value))
                {
                    var previousValue = _tramite;
                    _tramite = value;
                    FixupTramite(previousValue);
                }
            }
        }
        private Tramite _tramite;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTramite(Tramite previousValue)
        {
            if (previousValue != null && previousValue.Tupa.Contains(this))
            {
                previousValue.Tupa.Remove(this);
            }
    
            if (Tramite != null)
            {
                if (!Tramite.Tupa.Contains(this))
                {
                    Tramite.Tupa.Add(this);
                }
                if (codigoTramite != Tramite.codigo)
                {
                    codigoTramite = Tramite.codigo;
                }
            }
            else if (!_settingFK)
            {
                codigoTramite = null;
            }
        }

        #endregion
    }
}
