//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDNegocio.WSSolicitante {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSolicitante.ISolicitante")]
    public interface ISolicitante {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitante/ListarSolicitante", ReplyAction="http://tempuri.org/ISolicitante/ListarSolicitanteResponse")]
        System.Collections.Generic.List<STDDatos.Solicitante> ListarSolicitante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitante/ObtenerSolicitante", ReplyAction="http://tempuri.org/ISolicitante/ObtenerSolicitanteResponse")]
        System.Collections.Generic.List<STDDatos.Solicitante> ObtenerSolicitante(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISolicitante/AgregarSolicitante", ReplyAction="http://tempuri.org/ISolicitante/AgregarSolicitanteResponse")]
        string AgregarSolicitante(STDDatos.Solicitante pSolicitante, ref int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISolicitanteChannel : STDNegocio.WSSolicitante.ISolicitante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitanteClient : System.ServiceModel.ClientBase<STDNegocio.WSSolicitante.ISolicitante>, STDNegocio.WSSolicitante.ISolicitante {
        
        public SolicitanteClient() {
        }
        
        public SolicitanteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitanteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitanteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitanteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<STDDatos.Solicitante> ListarSolicitante() {
            return base.Channel.ListarSolicitante();
        }
        
        public System.Collections.Generic.List<STDDatos.Solicitante> ObtenerSolicitante(int codigo) {
            return base.Channel.ObtenerSolicitante(codigo);
        }
        
        public string AgregarSolicitante(STDDatos.Solicitante pSolicitante, ref int codigo) {
            return base.Channel.AgregarSolicitante(pSolicitante, ref codigo);
        }
    }
}
