//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDNegocio.WSCargo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCargo.ICargo")]
    public interface ICargo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargo/ObtenerCargo", ReplyAction="http://tempuri.org/ICargo/ObtenerCargoResponse")]
        System.Collections.Generic.List<STDDatos.Cargo> ObtenerCargo(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargo/ObtenerNuevoCodigo", ReplyAction="http://tempuri.org/ICargo/ObtenerNuevoCodigoResponse")]
        int ObtenerNuevoCodigo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICargo/AgregarCargo", ReplyAction="http://tempuri.org/ICargo/AgregarCargoResponse")]
        bool AgregarCargo(STDDatos.Cargo pCargo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICargoChannel : STDNegocio.WSCargo.ICargo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CargoClient : System.ServiceModel.ClientBase<STDNegocio.WSCargo.ICargo>, STDNegocio.WSCargo.ICargo {
        
        public CargoClient() {
        }
        
        public CargoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CargoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CargoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<STDDatos.Cargo> ObtenerCargo(int codigo) {
            return base.Channel.ObtenerCargo(codigo);
        }
        
        public int ObtenerNuevoCodigo() {
            return base.Channel.ObtenerNuevoCodigo();
        }
        
        public bool AgregarCargo(STDDatos.Cargo pCargo) {
            return base.Channel.AgregarCargo(pCargo);
        }
    }
}
