//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDNegocio.WSTramite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTramite.ITramite")]
    public interface ITramite {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITramite/ListarTramites", ReplyAction="http://tempuri.org/ITramite/ListarTramitesResponse")]
        System.Collections.Generic.List<STDDatos.Tramite> ListarTramites();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITramiteChannel : STDNegocio.WSTramite.ITramite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TramiteClient : System.ServiceModel.ClientBase<STDNegocio.WSTramite.ITramite>, STDNegocio.WSTramite.ITramite {
        
        public TramiteClient() {
        }
        
        public TramiteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TramiteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TramiteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TramiteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<STDDatos.Tramite> ListarTramites() {
            return base.Channel.ListarTramites();
        }
    }
}
