//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDNegocio.WSTupa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTupa.ITupa")]
    public interface ITupa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITupa/ObtenerTupa", ReplyAction="http://tempuri.org/ITupa/ObtenerTupaResponse")]
        System.Collections.Generic.List<STDDatos.Tupa> ObtenerTupa(int codigoTramite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITupaChannel : STDNegocio.WSTupa.ITupa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TupaClient : System.ServiceModel.ClientBase<STDNegocio.WSTupa.ITupa>, STDNegocio.WSTupa.ITupa {
        
        public TupaClient() {
        }
        
        public TupaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TupaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TupaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TupaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<STDDatos.Tupa> ObtenerTupa(int codigoTramite) {
            return base.Channel.ObtenerTupa(codigoTramite);
        }
    }
}
