//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STDNegocio.WSExpediente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSExpediente.IExpediente")]
    public interface IExpediente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpediente/AgregarExpediente", ReplyAction="http://tempuri.org/IExpediente/AgregarExpedienteResponse")]
        bool AgregarExpediente(ref STDDatos.Expediente pExpediente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpediente/ObtenerExpediente", ReplyAction="http://tempuri.org/IExpediente/ObtenerExpedienteResponse")]
        System.Collections.Generic.List<STDDatos.Expediente> ObtenerExpediente(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpedienteChannel : STDNegocio.WSExpediente.IExpediente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpedienteClient : System.ServiceModel.ClientBase<STDNegocio.WSExpediente.IExpediente>, STDNegocio.WSExpediente.IExpediente {
        
        public ExpedienteClient() {
        }
        
        public ExpedienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpedienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpedienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpedienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarExpediente(ref STDDatos.Expediente pExpediente) {
            return base.Channel.AgregarExpediente(ref pExpediente);
        }
        
        public System.Collections.Generic.List<STDDatos.Expediente> ObtenerExpediente(int codigo) {
            return base.Channel.ObtenerExpediente(codigo);
        }
    }
}
